apiVersion: v1
kind: Service
metadata:
  name: bff-nodejs-mobile-g
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8090'
  labels:
    app: bff-nodejs-mobile
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 3000
  - name: nodejs-exporter
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: bff-nodejs-mobile
    version: '1.52'
  type: ClusterIP
